name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  SGX_MODE: SW
  IAS_MODE: DEV

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: ⚙ Install protobuf compiler
        run: |
          sudo apt install -y protobuf-compiler

      - uses: actions/checkout@v4
      - name: ⚡ Cargo Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/checkout@v4

      - name: 🔬 Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: 0.22.0

      - name: 🆙 Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: 💾 Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: cobertura.xml
